
  var Data = [{
  "id": 1,
  "image": "https://img-a.udemycdn.com/course/240x135/2127358_0047_5.jpg",
  "tittle": "eBook and Paperback Book Cover Design Using Canva and Gimp",
  "host": "Karen Prince",
  "description": "Self-Publishing? Create your own professional looking book covers; ready to upload to major retailers and distributors.",
  "price": "39.99",
},{
  "id": 2,
  "image": "https://img-a.udemycdn.com/course/240x135/2887266_c696_5.jpg",
  "tittle": "Write a Bestselling Novel in 15 Steps (Writing Mastery)",
  "host": "Jessica Prince",
  "description": "Self-Publishing? Create your own professional looking book covers; ready to upload to major retailers and distributors.",
  "price": "49.99",
},{
  "id": 3,
  "image": "https://img-a.udemycdn.com/course/240x135/1026604_790b_2.jpg",
  "tittle": "eBook and Paperback Book Cover Design Using Canva and Gimp",
  "host": "Rahim Prince",
  "description": "Self-Publishing? Create your own professional looking book covers; ready to upload to major retailers and distributors.",
  "price": "69.99",
},{
  "id": 4,
  "image": "https://img-a.udemycdn.com/course/240x135/1778502_f4b9_11.jpg",
  "tittle": "eBook and Paperback Book Cover Design Using Canva and Gimp",
  "host": "Json Khan",
  "description": "Self-Publishing? Create your own professional looking book covers; ready to upload to major retailers and distributors.",
  "price": "79.99",
},{
  "id": 5,
  "image": "https://img-a.udemycdn.com/course/240x135/1393656_3b04_5.jpg",
  "tittle": "After Effects: The Complete Beginner Course (All Versions)",
  "host": "Krish Khan",
  "description": "Learn How to Create Professional Motion Graphics & Animations. Add Exciting Visual Effects to Your Own Video Projects",
  "price": "79.99",
},{
  "id": 6,
  "image": "https://img-a.udemycdn.com/course/240x135/2127358_0047_5.jpg",
  "tittle": "eBook and Paperback Book Cover Design Using Canva and Gimp",
  "host": "Karim Khan",
  "description": "Self-Publishing? Create your own professional looking book covers; ready to upload to major retailers and distributors.",
  "price": "39.99",
},{
  "id": 7,
  "image": "https://img-a.udemycdn.com/course/240x135/1503082_610c_4.jpg",
  "tittle": "Android Dependency Injection with Dagger 2",
  "host": "Kabbo Khan",
  "description": "Master Dagger 2 Android Dependency Injection framework and start writing clean Android applications",
  "price": "79.99",
},{
  "id": 8,
  "image": "https://img-a.udemycdn.com/course/240x135/2647524_796d_5.jpg",
  "tittle": "2D Character Animation: Walk Cycles",
  "host": "Morshedul Munna",
  "description": "Design Characters for animation in Adobe Animate : animate a character step by step : animate a full scene",
  "price": "19.99",
},{
  "id": 9,
  "image": "https://img-a.udemycdn.com/course/240x135/1778502_f4b9_11.jpg",
  "tittle": "iOS 13 & Swift 5 - The Complete iOS App Development Bootcamp",
  "host": "Minal Prodhan",
  "description": "From Beginner to iOS App Developer with Just One Course! Fully Updated with a Comprehensive Module Dedicated to SwiftUI!",
  "price": "49.99",
},{
  "id": 10,
  "image": "https://img-a.udemycdn.com/course/240x135/2127358_0047_5.jpg",
  "tittle": "eBook and Paperback Book Cover Design Using Canva and Gimp",
  "host": "Karen Prince",
  "description": "Self-Publishing? Create your own professional looking book covers; ready to upload to major retailers and distributors.",
  "price": "89.99",
},{
  "id": 11,
  "image": "https://img-a.udemycdn.com/course/240x135/2127358_0047_5.jpg",
  "tittle": "eBook and Paperback Book Cover Design Using Canva and Gimp",
  "host": "Karen Prince",
  "description": "Self-Publishing? Create your own professional looking book covers; ready to upload to major retailers and distributors.",
  "price": "29.99",
},{
  "id": 12,
  "image": "https://img-a.udemycdn.com/course/240x135/2127358_0047_5.jpg",
  "tittle": "eBook and Paperback Book Cover Design Using Canva and Gimp",
  "host": "Karen Prince",
  "description": "Self-Publishing? Create your own professional looking book covers; ready to upload to major retailers and distributors.",
  "price": "69.99",
},{
  "id": 13,
  "image": "https://img-a.udemycdn.com/course/240x135/2127358_0047_5.jpg",
  "tittle": "eBook and Paperback Book Cover Design Using Canva and Gimp",
  "host": "Karen Prince",
  "description": "Self-Publishing? Create your own professional looking book covers; ready to upload to major retailers and distributors.",
  "price": "39.69",
},{
  "id": 14,
  "image": "https://img-a.udemycdn.com/course/240x135/2127358_0047_5.jpg",
  "tittle": "eBook and Paperback Book Cover Design Using Canva and Gimp",
  "host": "Karen Prince",
  "description": "Self-Publishing? Create your own professional looking book covers; ready to upload to major retailers and distributors.",
  "price": "49.59",
},{
  "id": 15,
  "image": "https://img-a.udemycdn.com/course/240x135/2127358_0047_5.jpg",
  "tittle": "eBook and Paperback Book Cover Design Using Canva and Gimp",
  "host": "Karen Prince",
  "description": "Self-Publishing? Create your own professional looking book covers; ready to upload to major retailers and distributors.",
  "price": "39.99",
},{
  "id": 16,
  "image": "https://img-a.udemycdn.com/course/240x135/2127358_0047_5.jpg",
  "tittle": "eBook and Paperback Book Cover Design Using Canva and Gimp",
  "host": "Karen Prince",
  "description": "Self-Publishing? Create your own professional looking book covers; ready to upload to major retailers and distributors.",
  "price": "45.99",
},{
  "id": 17,
  "image": "https://img-a.udemycdn.com/course/240x135/2127358_0047_5.jpg",
  "tittle": "eBook and Paperback Book Cover Design Using Canva and Gimp",
  "host": "Karen Prince",
  "description": "Self-Publishing? Create your own professional looking book covers; ready to upload to major retailers and distributors.",
  "price": "29.99",
},{
  "id": 18,
  "image": "https://img-a.udemycdn.com/course/240x135/2127358_0047_5.jpg",
  "tittle": "eBook and Paperback Book Cover Design Using Canva and Gimp",
  "host": "Karen Prince",
  "description": "Self-Publishing? Create your own professional looking book covers; ready to upload to major retailers and distributors.",
  "price": "29.99",
},{
  "id": 19,
  "image": "https://img-a.udemycdn.com/course/240x135/2127358_0047_5.jpg",
  "tittle": "eBook and Paperback Book Cover Design Using Canva and Gimp",
  "host": "Karen Prince",
  "description": "Self-Publishing? Create your own professional looking book covers; ready to upload to major retailers and distributors.",
  "price": "29.99",
},{
  "id": 20,
  "image": "https://img-a.udemycdn.com/course/240x135/2127358_0047_5.jpg",
  "tittle": "eBook and Paperback Book Cover Design Using Canva and Gimp",
  "host": "Karen Prince",
  "description": "Self-Publishing? Create your own professional looking book covers; ready to upload to major retailers and distributors.",
  "price": "29.99",
},{
  "id": 21,
  "image": "https://img-a.udemycdn.com/course/240x135/2127358_0047_5.jpg",
  "tittle": "eBook and Paperback Book Cover Design Using Canva and Gimp",
  "host": "Karen Prince",
  "description": "Self-Publishing? Create your own professional looking book covers; ready to upload to major retailers and distributors.",
  "price": "29.99",
},{
  "id": 22,
  "image": "https://img-a.udemycdn.com/course/240x135/2127358_0047_5.jpg",
  "tittle": "eBook and Paperback Book Cover Design Using Canva and Gimp",
  "host": "Karen Prince",
  "description": "Self-Publishing? Create your own professional looking book covers; ready to upload to major retailers and distributors.",
  "price": "29.99",
},{
  "id": 23,
  "image": "https://img-a.udemycdn.com/course/240x135/2127358_0047_5.jpg",
  "tittle": "eBook and Paperback Book Cover Design Using Canva and Gimp",
  "host": "Karen Prince",
  "description": "Self-Publishing? Create your own professional looking book covers; ready to upload to major retailers and distributors.",
  "price": "29.99",
},{
  "id": 24,
  "image": "https://img-a.udemycdn.com/course/240x135/2127358_0047_5.jpg",
  "tittle": "eBook and Paperback Book Cover Design Using Canva and Gimp",
  "host": "Karen Prince",
  "description": "Self-Publishing? Create your own professional looking book covers; ready to upload to major retailers and distributors.",
  "price": "29.99",
},{
  "id": 25,
  "image": "https://img-a.udemycdn.com/course/240x135/2127358_0047_5.jpg",
  "tittle": "eBook and Paperback Book Cover Design Using Canva and Gimp",
  "host": "Karen Prince",
  "description": "Self-Publishing? Create your own professional looking book covers; ready to upload to major retailers and distributors.",
  "price": "29.99",
}]

export default Data;